### ISSUE TITLE
Controllers for main app

### ISSUE THREAD

**Issue by JeanetteMoKa** [AVG-E-Z/savings-sage#13]

**Comment by kveszti** [comment]
- BankAccount controller -- post, (hardcoded userId for now?), delete, getAll
- TransactionController -- post, delete, getAllForAccount, getAll

**Comment by kveszti** [comment]
BankAccount - Zsani
Transaction - Eszti

**Comment by JeanetteMoKa** [comment]
- [ ] Bank Account Unit Test
- [ ] Transaction Unit Test
